version: "3.3"

services:
  apache:
    build: ./apache
    volumes:
      - ./apache/logs:/var/log/apache2
    ports:
      - "8010:80"
  
  postgres:
    image: postgres:12
    env_file: ./.env
    # ログの吐き出し先をコンテナ内のファイルにする
    command: 'postgres -c port="5432" -c log_statement=all -c log_destination=stderr -c log_connections=on -c log_disconnections=on -c logging_collector=on -c log_filename=postgresql.log'
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fluentd:
    build: ./fluentd
    env_file: ./.env
    command: --use-v1-config # rubyコード埋め込めるようにする
    volumes:
      - ./fluentd/config:/fluentd/etc
      - ./postgres/pgdata/log:/var/log/postgres
      - ./apache/logs:/var/log/apache
    ports:
      - "24224:24224"
    links:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.3.2
    environment:
      - discovery.type=single-node
      - cluster.routing.allocation.disk.watermark.low=95% # ホストマシンのディスク枯渇対応
      - cluster.routing.allocation.disk.watermark.high=95% # ホストマシンのディスク枯渇対応
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.3.2
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
